# Generated by Django 4.2.23 on 2025-08-02 15:51

from django.db import migrations, models
import teams.models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='invite_code',
            field=models.CharField(default=teams.models.generate_invite_code, max_length=6, unique=True),
        ),
    ]
