# Generated by Django 4.2.23 on 2025-08-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ai_roles_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
