# Generated by Django 4.2.23 on 2025-08-11 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_invite_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0002_memberroleassignment_assigned_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=100)),
                ('traits', models.JSONField(default=list)),
                ('preferences', models.JSONField(default=list)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('team', 'user')},
            },
        ),
    ]
